services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', '${POSTGRES_USER} -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  www:
    container_name: weather
    build:
      dockerfile: Dockerfile
      context: .
    env_file: ./.env
    #volumes:
      #- static_volume:/www/src/weather/project/static
    working_dir: /www/src/weather
    command:
      - bash
      - -c
      - |
        python3 ./manage.py collectstatic --noinput
        python3 ./manage.py makemigrations
        python3 ./manage.py migrate
        gunicorn -w 4 --bind 0.0.0.0:8000 project.wsgi:application
    volumes:
      - static_volume:/www/src/weather/project/static
    depends_on:
      - db
    ports:
      - "8000:8000"
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - www
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - static_volume:/var/www/src/weather/project/static
    restart: on-failure

volumes:
  postgres_data:
    external: true
  static_volume:
    external: true
