# Generated by Django 4.2.17 on 2025-05-25 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="latitude",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="latitude for forecast",
                max_length=7,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        7,
                        message="Maximum quantity of symbols before 7 symbols/characters",
                    ),
                    django.core.validators.MinLengthValidator(
                        2, message="Minimum quantity of symbols is 2 symbols/characters"
                    ),
                ],
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="longitude",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="longitude for forecast",
                max_length=7,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        7,
                        message="Maximum quantity of symbols before 7 symbols/characters",
                    ),
                    django.core.validators.MinLengthValidator(
                        2, message="Minimum quantity of symbols is 2 symbols/characters"
                    ),
                ],
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        7,
                        message="Maximum quantity of symbols before 7 symbols/characters",
                    ),
                    django.core.validators.MinLengthValidator(
                        2, message="Minimum quantity of symbols is 2 symbols/characters"
                    ),
                    django.core.validators.RegexValidator(
                        message="The password's characters is valid",
                        regex="(^[a-zA-Z%0-9}{_%]{2,30}$|^$)",
                    ),
                ],
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="Name should be at least 3 characters"
                    ),
                    django.core.validators.MaxLengthValidator(
                        30, "Name should be less than 30  or 30 characters"
                    ),
                    django.core.validators.RegexValidator(
                        message="Name should contain only charactersfrom a-z and A-Z and digits",
                        regex="(^[a-zA-Z][a-zA-Z_]{2,30}$|^$)",
                    ),
                ],
                verbose_name="username",
            ),
        ),
    ]
