# Generated by Django 4.2.17 on 2025-05-24 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField(blank=True, help_text='latitude for forecast', max_length=7, validators=[django.core.validators.MaxLengthValidator(7, message='Maximum quantity of symbols before 7 symbols/characters'), django.core.validators.MinLengthValidator(2, message='Minimum quantity of symbols is 2 symbols/characters')])),
                ('longitude', models.FloatField(blank=True, help_text='longitude for forecast', max_length=7, validators=[django.core.validators.MaxLengthValidator(7, message='Maximum quantity of symbols before 7 symbols/characters'), django.core.validators.MinLengthValidator(2, message='Minimum quantity of symbols is 2 symbols/characters')])),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Date when user is last time used the service')),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
                'db_table': 'weather',
            },
        ),
    ]
