# Generated by Django 4.2.17 on 2025-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherforecast",
            name="user_id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
