name: Django_weather
on:
  push:
    branches: ['dev']

jobs:
  deploy_weather:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ '3.x' ]
      steps:
        # cache remove
        - name: Clear GitHub Actions cache
          run: rm -rf $HOME/.cache/actions
  cicd_deploy:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ '3.x' ]
      env:
        DEPLOY_HOST: ${{ secrets.LOCAL_HOST }}
        DEPLOY_USER: ${{ secrets.LOCAL_USER }}
        DEPLOY_PASSWORD: ${{ secrets.LOCAL_PASS }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      steps:
        - name: Deploy to GitHub Pages
          uses: appleboy/ssh-action@master
          with:
            host: ${{env.DEPLOY_HOST}}
            username: ${{ env.DEPLOY_USER }} # пользователь сервера
            key: ${{ env.SSH_PRIVATE_KEY }}
            password: ${{ env.DEPLOY_PASSWORD }}
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              bash /home/denis/weather/pull.sh
